#!/bin/bash

if [ "$#" -eq 1 ]; then
    HOST=$1
else
    echo "Usage: $0 <host>"
    exit 1
fi

ssh -o ControlPath=~/.ssh/ctl/%L-%r@%h:%p -O check ${HOST} 2>/dev/null
SSH_STATUS=$?

if [ $SSH_STATUS -ne 0 ]; then
    echo "ControlMaster not active. "
else
    ssh -O exit -o "ControlPath=~/.ssh/ctl/%L-%r@%h:%p" $HOST
fi

